spring:
    datasource:
        url: jdbc:mysql://localhost:3306/vine_wears?useSSL=false&serverTimezone=UTC
        username: root
        password: password1234

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy:
              org:
                hibernate:
                  cfg: ImprovedNamingStrategy
            temp:
              use_jdbc_metadata_defaults: false
        properties:
            hibernate:
              enable_lazy_load_no_trans: true
              jdbc:
                lob:
                  non_contextual_creation: true

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 944957257869-u2cethmph9dvlah5g11pdc6s5u85qut2.apps.googleusercontent.com
              clientSecret: Kmn4xXLuPpIjTaO-2c_Oqlpb
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 201361571812365
              clientSecret: 5d805a6708a2d499f1423d63168fb01f
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

server:
  error:
    include-binding-errors: always

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBCWKdsgfsrtwrete6..54grsregfsh=======0-kuyfdhjdfhbshfdbmmdDFGADAQFGTGSFDHBDTFGHNYYHDYH&GSHGHSGHSGBGJKLYUPLI-_======UKYJTHARBFBSAQWAVZFBGNSH926D96C90030DD58429D2751AC1BDBBCWKdsgfsrtwrete654grsregfsh=======0-kuyfdhjdfhbshfdbmmdDFGADAQFGTGSFDHBDTFGHNYYHDYH&GSHGHSGHSGBGJKLYUPLI-_======UKYJTHARBFBSAQWAVZFBGNSH926D96C90030DD58429D2751AC1BDBBCWKdsgfsrtwrete654grsregfsh=======0-kuyfdhjdfhbshfdbmmdDFGADAQFGTGSFDHBDTFGHNYYHDYH&GSHGHSGHSGBGJKLYUPLI-_======UKYJTHARBFBSAQWAVZFBGNSH
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3005/oauth2/redirect

cloudinary:
  cloud_name: divineworld
  api_key: 992938727429154
  api_secret: FLStrE6YBi_QqSOn3Gq8lI2vHFQ